name = "UKSF Air"
prefix = "uksf_air"
author = "UKSF SR3 Team"
files = [
    "mod.cpp",
    "mod.paa",
    "modLarge.paa",
    "README.md",
    "AUTHORS.txt",
    "LICENSE"
]

modname = "uksf_air"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

check = [
    "!version_set",
    "!binarizer_link"
]
releasebuild = [
    "@zip uksf_air_v{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

# Binarizer file search compatibility
[scripts.binarizer_link]
steps_windows = [
    "if not exist u\\uksf_air mkdir u\\uksf_air",
    "if not exist u\\uksf_air\\addons mklink /j u\\uksf_air\\addons addons",
    "if not exist a3 mklink /j a3 include\\a3"
]
steps_linux = [
    # Preparation for Windows Binarizer (run once on Linux for network share compatibility)
    "mkdir -p u/uksf_air",
    "[ -d u/uksf_air/addons ] || ln -sr addons u/uksf_air/",
    "mkdir -p a3",
    "[ -d a3 ] || ln -sr include/a3 a3/"
]
show_output = true
