HIDE_CLASS_WITH_BASE(CUP_B_GR9_DYN_GB,CUP_GR9_DYN_Base);
HIDE_CLASS_WITH_BASE(CUP_B_GR9_CAP_GB,CUP_AV8B_Base);
HIDE_CLASS(CUP_B_GR9_Mk82_GB,CUP_AV8B_Base);
HIDE_CLASS(CUP_B_GR9_GBU12_GB,CUP_AV8B_Base);
HIDE_CLASS(CUP_B_GR9_AGM_GB,CUP_AV8B_Base);
